package com.vineethraj.cattranslator.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val BrandPrimaryLight = Color(0xFFB5502D)
val BrandOnPrimaryLight = Color(0xFFFFFFFF)
val BrandPrimaryContainerLight = Color(0xFFFFDBC9)
val BrandOnPrimaryContainerLight = Color(0xFF3B0D00)
val BrandSecondaryLight = Color(0xFF6B5B4D)
val BrandOnSecondaryLight = Color(0xFFFFFFFF)
val BrandTertiaryLight = Color(0xFF44654F)
val BrandOnTertiaryLight = Color(0xFFFFFFFF)
val BrandBackgroundLight = Color(0xFFFBF7F3)
val BrandOnBackgroundLight = Color(0xFF231A15)
val BrandSurfaceLight = Color(0xFFFFFFFF)
val BrandOnSurfaceLight = Color(0xFF231A15)
val BrandSurfaceVariantLight = Color(0xFFF1E0D6)
val BrandOnSurfaceVariantLight = Color(0xFF52443C)
val BrandOutlineLight = Color(0xFF85736A)
val BrandErrorLight = Color(0xFFBA1A1A)
val BrandOnErrorLight = Color(0xFFFFFFFF)

// Dark scheme
val BrandPrimaryDark = Color(0xFFFFB59A)
val BrandOnPrimaryDark = Color(0xFF5F1B00)
val BrandPrimaryContainerDark = Color(0xFF873600)
val BrandOnPrimaryContainerDark = Color(0xFFFFDBC9)
val BrandSecondaryDark = Color(0xFFD7C3B3)
val BrandOnSecondaryDark = Color(0xFF3B2D21)
val BrandTertiaryDark = Color(0xFFAAD1B2)
val BrandOnTertiaryDark = Color(0xFF163723)
val BrandBackgroundDark = Color(0xFF16130F)
val BrandOnBackgroundDark = Color(0xFFEDE0D9)
val BrandSurfaceDark = Color(0xFF211D18)
val BrandOnSurfaceDark = Color(0xFFEDE0D9)
val BrandSurfaceVariantDark = Color(0xFF52443C)
val BrandOnSurfaceVariantDark = Color(0xFFD5C3B8)
val BrandOutlineDark = Color(0xFF9E8D83)
val BrandErrorDark = Color(0xFFFFB4AB)
val BrandOnErrorDark = Color(0xFF690005)
